# standard jekyll configuration

baseurl:   http://dbindel.github.com

permalink: date
pygments: true
exclude: ['Rakefile', 'README.md']
markdown: kramdown

# configuration required for some pages

domain: dbindel.github.com
title: Eigenmumbles
author: David Bindel
email: bindel@cs.cornell.edu

# configuration for ehancements, uncomment to enable

# feedburner:
#   id: feedburnerid

# google_analytics:
#   account: UA-XXXXX-X

# github:
#   username: ghusername

disqus:
   id: eigenmumbles
