# standard jekyll configuration

baseurl:   http://www.dbindel.net

permalink: date
exclude: ['Rakefile', 'README.md']
markdown: kramdown

# configuration required for some pages

domain: www.dbindel.net
title: Eigenmumbles
author: David Bindel
email: bindel@cs.cornell.edu

# configuration for ehancements, uncomment to enable

# feedburner:
#   id: feedburnerid

# google_analytics:
#   account: UA-XXXXX-X

# github:
#   username: ghusername

disqus:
   id: eigenmumbles
